# Site settings
title: Woody2143
email: woody@2143.net
description: > # this means to ignore newlines until "baseurl:"
  Github page for my profile, Woody2143. Likely to contain random posts
  about whatever I'm working on that week. Figure that this is a good a
  place to blog as any.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://woody2143.github.io" # the base hostname & protocol for your site
twitter_username: woody2143
github_username:  woody2143

highlighter: pygments
github: [Repository metadata]

# Build settings
markdown: kramdown
